name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - uses: azure/login@v1
        with:
          # probot/example-azure-function credentials provided by @gr2m
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "probot-example"
          package: "."
          # probot/example-azure-function credentials provided by @gr2m
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
